version: '3.4'

services:
  justbank:
    image: justbank
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - PORT=8000
      # Test purpose
      - DB_USER=just_bank_user
      - DB_PASSWORD=password
      - DB_NAME=just_bank_db
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
    networks:
      - default
