
### All
GET http://localhost:8000/customers


### Active
GET http://localhost:8000/customers?status=active

### Inactive
GET http://localhost:8000/customers?status=inactive

###
GET http://localhost:8000/customers/2000

### Resource not found

GET http://localhost:8000/customers/A-1000

###

POST http://localhost:8000/customers